//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMp3Importer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tInfo()
        {
            this.tSongs = new HashSet<tSong>();
        }
    
        public int ID { get; set; }
        public int ID_Song { get; set; }
        public Nullable<int> Played { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Beat { get; set; }
        public Nullable<bool> Error { get; set; }
        public Nullable<bool> Sampler { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Media { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSong> tSongs { get; set; }
    }
}
