//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMp3Importer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTestImport
    {
        public int ID { get; set; }
        public string Katalog { get; set; }
        public string Medium { get; set; }
        public string Album { get; set; }
        public string Interpret { get; set; }
        public string Titel { get; set; }
        public string Genre { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public string Pfad { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsSampler { get; set; }
        public string MD5 { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
